perf!(project): various performance improvements across the project

diff --git a/bin/vb-app-syncthing b/bin/vb-app-syncthing
--- a/bin/vb-app-syncthing
+++ b/bin/vb-app-syncthing
@@ -1,35 +1,21 @@
 #!/usr/bin/env bash
 
-source vb-core-lib
-
 if ! command -v syncthing > /dev/null; then
-    if term::is_headless; then
-        notify-send -r 4 -u critical -t 5000 "Vibranium" "Syncthing is not installed!"
+    if [[ ! -t 1 ]]; then
+        notify-send -r 4 -u critical -t 5000 \
+        "Vibranium" "Syncthing is not installed!"
     fi
-    log::error "Syncthing is not installed!"
+
+    echo "error: syncthing is not installed!" >&2
     exit 1
 fi
 
-# If the user launches Syncthing, but the service is not active / not enabled
-if ! pidof -q syncthing; then
-    if [ "$(systemctl --user is-active syncthing)" != "active" ]; then
-        systemctl --user enable --now syncthing
-        # Wait until the service starts up
-        sleep 0.5
-
-        msg="<b>Syncthing</b> systemd service wasn't active.\n"
-        msg+="The service has been enabled and started for you.\n\n"
-        msg+="This notification is one-time event.\nIf you see this every time you launch <b>Syncthing</b>,\n"
-        msg+="then consider checking logs by executing:\n\n"
-        msg+="<span foreground='${P_GREEN}'>systemctl</span> <span foreground='${P_YELLOW}'>--user</span> "
-        msg+="<span foreground='${P_ORANGE}'>status</span> <span foreground='${P_BLUE}'>syncthing.service</span>"
-        notify-send -r 1 "Vibranium" -t 15000 "$msg"
-    fi
+if ! systemctl -q --user is-active syncthing; then
+    systemctl -q --user enable --now syncthing
 fi
 
 if command -v chromium > /dev/null; then
     vb-cmd-launch-cmd chromium --app="https://127.0.0.1:8384"
-    # exec setsid uwsm app -- chromium --app="https://127.0.0.1:8384"
 else
     syncthing browser
 fi
diff --git a/bin/vb-cmd-get-wallpaper b/bin/vb-cmd-get-wallpaper
--- a/bin/vb-cmd-get-wallpaper
+++ b/bin/vb-cmd-get-wallpaper
@@ -14,18 +14,29 @@ Options:
 EOF
 }
 
+
 get_wallpaper() {
     sed -n 's/^wallpaper:path = //p' "$hyprpaper_conf"
 }
 
 case "$1" in
     -b|--basename)
+        if ! systemctl -q --user is-active hyprpaper; then
+            echo "error: wallpaper deamon is not active!" >&2
+            exit 1
+        fi
+
         get_wallpaper | xargs -r basename
         ;;
     -h|--help)
         usage
         ;;
     "" )
+        if ! systemctl -q --user is-active hyprpaper; then
+            echo "error: wallpaper deamon is not active!" >&2
+            exit 1
+        fi
+
         get_wallpaper
         ;;
     * )
