refactor!: migrate to xdg-terminal-exec & app2unit

diff --git a/bin/vb-cmd-networkmanager b/bin/vb-cmd-networkmanager
--- a/bin/vb-cmd-networkmanager
+++ b/bin/vb-cmd-networkmanager
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 usage() {
-  cat << EOF
+  cat <<EOF
 Usage: ${0##*/} [OPTION]
 
 Launch UI / TUI for the active network manager.
@@ -12,30 +12,30 @@ EOF
 }
 
 case "$1" in
-  -h | --help)
-    usage
-    exit 0
-    ;;
-  "") ;;
-  *)
-    echo "${0##*/}: invalid option '$1'" >&2
-    echo "Try '${0##*/} --help' for more information." >&2
-    exit 1
-    ;;
+-h | --help)
+  usage
+  exit 0
+  ;;
+"") ;;
+*)
+  echo "${0##*/}: invalid option '$1'" >&2
+  echo "Try '${0##*/} --help' for more information." >&2
+  exit 1
+  ;;
 esac
 
 # Detect primary network interface utility
-if command -v nmtui > /dev/null 2>&1; then
-  exec vb-core-term --floating -- nmtui
-elif command -v iwctl > /dev/null 2>&1; then
-  if command -v impala > /dev/null 2>&1; then
-    exec vb-core-term --floating -- impala
-  elif command -v iwmenu > /dev/null 2>&1; then
-    vb-cmd-launch-cmd iwmenu
-  elif command -v iwgtk > /dev/null 2>&1; then
-    vb-cmd-launch-cmd iwgtk
+if command -v nmtui >/dev/null 2>&1; then
+  xdg-terminal-exec --app-id=org.vb.term.float --title=nmtui -- nmtui
+elif command -v iwctl >/dev/null 2>&1; then
+  if command -v impala >/dev/null 2>&1; then
+    xdg-terminal-exec --app-id=org.vb.term.float --title=impala -- impala
+  elif command -v iwmenu >/dev/null 2>&1; then
+    app2unit iwmenu
+  elif command -v iwgtk >/dev/null 2>&1; then
+    app2unit iwgtk
   else
-    exec vb-core-term --floating -- iwctl
+    xdg-terminal-exec --app-id=org.vb.term.float --title=iwctl -- iwctl
   fi
 else
   if systemctl -q is-active systemd-networkd; then
diff --git a/bin/vb-tweak-spotify b/bin/vb-tweak-spotify
--- a/bin/vb-tweak-spotify
+++ b/bin/vb-tweak-spotify
@@ -8,12 +8,12 @@ ACTION="$1"
 progress() {
   local msg="$1"
   case "$msg" in
-    clear)
-      rm -f "$VIBRNAIUM_RUNTIME/worker.active"
-      ;;
-    *)
-      echo "$msg" > "$VIBRNAIUM_RUNTIME/worker.active"
-      ;;
+  clear)
+    rm -f "$VIBRNAIUM_RUNTIME/worker.active"
+    ;;
+  *)
+    echo "$msg" >"$VIBRNAIUM_RUNTIME/worker.active"
+    ;;
   esac
   vb-cmd-refresh-bar-module worker
 }
@@ -25,7 +25,7 @@ fail() {
   msg+="\n<b><i>Click here to see logs</i></b>"
 
   if [[ "$(notify-send -A true -r 4 -t 10000 -u critical 'Vibranium' "$msg")" == 0 ]]; then
-    vb-core-term -- "$EDITOR" "$LOGFILE"
+    xdg-terminal-exec -- "${EDITOR:-nvim}" "$LOGFILE"
   fi
   progress clear
   exit 1
@@ -37,11 +37,11 @@ install_adblock() {
 
   if [ ! -f "$FILE" ]; then
     curl -fsSL "https://raw.githubusercontent.com/rxri/spicetify-extensions/refs/heads/main/adblock/adblock.js" \
-      -o "$FILE" &> "$LOGFILE" || fail
+      -o "$FILE" &>"$LOGFILE" || fail
   fi
 
   spicetify -q config extensions adblock.js
-  spicetify -n apply &> "$LOGFILE" || fail
+  spicetify -n apply &>"$LOGFILE" || fail
 
   progress clear
   if pkill -0 spotify; then
@@ -71,10 +71,10 @@ remove_adblock() {
 }
 
 case "$ACTION" in
-  install) install_adblock ;;
-  remove) remove_adblock ;;
-  *)
-    echo "Usage: $0 {install|remove}" >&2
-    exit 1
-    ;;
+install) install_adblock ;;
+remove) remove_adblock ;;
+*)
+  echo "Usage: $0 {install|remove}" >&2
+  exit 1
+  ;;
 esac
