change things here and there

diff --git a/bin/vb-core-color-picker b/bin/vb-core-color-picker
--- a/bin/vb-core-color-picker
+++ b/bin/vb-core-color-picker
@@ -1,18 +1,5 @@
 #!/usr/bin/env bash
 
-source vb-core-lib
-
-if pid=$(pidof hyprpicker); then
-    kill $pid
-    exit 1
-fi
-
-if ! missing="$(vb-cmd-is-present hyprpicker)"; then
-    log::error "missing required dependencies: $missing"
-    term::is_headless && vb-cmd-dep-notify --name "Clipboard Manager" --deps "$missing"
-    exit 1
-fi
-
 HISTORY="$VIBRANIUM_CACHE/color-picker.history"
 
 usage() {
@@ -29,7 +16,15 @@ EOF
 
 clear_history() {
     : > "$HISTORY"
-    vb-cmd-refresh-bar-module color-picker
+    vb-cmd-refresh-bar-module color-picker &
+}
+
+check_deps() {
+    if ! command -v hyprpicker > /dev/null; then
+        echo "[ERROR] missing required dependencies: hyprpicker" >&2
+        vb-cmd-dep-notify --name "Color Picker" --deps "hyprpicker"
+        return 1
+    fi
 }
 
 case "$1" in
@@ -38,10 +33,12 @@ case "$1" in
         exit 0
         ;;
     -c|--clear)
+        check_deps || exit 1
         clear_history
         exit 0
         ;;
     "")
+        check_deps || exit 1
         :
         ;;
     *)
@@ -50,12 +47,19 @@ case "$1" in
         exit 1
 esac
 
+source vb-core-lib
+
 if [[ -f "$XDG_CONFIG_HOME/hypr/hyprland.conf.d/reading-mode.conf" ]]; then
     if term::is_headless; then
         msg="<b>Color Picker</b> isn't available while <b>Reading Mode</b> is active!"
         notify-send -r 2 -t 3000 "Color Picker" "$msg"
     fi
     log::error "Reading Mode is active. Aborting"
+    exit 1
+fi
+
+if pid=$(pidof hyprpicker); then
+    kill $pid
     exit 1
 fi
 
diff --git a/bin/vb-core-power b/bin/vb-core-power
--- a/bin/vb-core-power
+++ b/bin/vb-core-power
@@ -1,13 +1,5 @@
 #!/usr/bin/env bash
 
-source vb-core-lib
-
-if ! missing="$(vb-cmd-is-present powerprofilesctl)"; then
-    log::error "missing required dependencies: power-profiles-daemon"
-    term::is_headless && vb-cmd-dep-notify --name "Clipboard Manager" --deps "power-profiles-daemon"
-    exit 1
-fi
-
 usage() {
     cat <<EOF
 Usage: ${0##*/} [OPTION]
@@ -89,6 +81,14 @@ toggle_blur() {
     fi
 }
 
+_ensure_deps() {
+    if ! command -v powerprofilesctl > /dev/null; then
+        echo "[ERROR] Missing required dependencies: power-profiles-daemon"
+        vb-cmd-dep-notify --name "Power Management" --deps "power-profiles-daemon"
+        exit 1
+    fi
+}
+
 ACTION="next"
 QUIET="false"
 
@@ -122,6 +122,10 @@ while [[ $# -gt 0 ]]; do
             ;;
     esac
 done
+
+_ensure_deps
+
+source vb-core-lib
 
 # Cache defaults (for further validation)
 helpers::parse_defaults
