feat: rework the startup logic

diff --git a/bin/vb-core-brightness b/bin/vb-core-brightness
--- a/bin/vb-core-brightness
+++ b/bin/vb-core-brightness
@@ -29,7 +29,7 @@ shcat() {
 
 usage() {
   shcat <<EOF
-Usage: $SELF [--up|--down|--set <0-100>]
+Usage: $SELF [OPTIONS]
 
 Adjust screen brightness.
 
@@ -59,7 +59,6 @@ while [[ $# -gt 0 ]]; do
     # --set requires a following integer in the range 0-100
     if [[ ! "$2" =~ ^[0-9]+$ ]] || (($2 < 0 || $2 > 100)); then
       echo "Error: --set requires an integer between 0 and 100" >&2
-      usage
       exit 1
     fi
     ACTION="$1"
@@ -71,7 +70,8 @@ while [[ $# -gt 0 ]]; do
     shift
     ;;
   *)
-    usage
+    echo "Error: unknown option: $@" >&2
+    echo "Try '${0##*/} --help' for more information" >&2
     exit 1
     ;;
   esac
diff --git a/bin/vb-util-calc b/bin/vb-util-calc
--- a/bin/vb-util-calc
+++ b/bin/vb-util-calc
@@ -1,9 +1,45 @@
 #!/usr/bin/bash
 
-exec 9> "$VIBRANIUM_RUNTIME/${0##*/}.lock"
+SELF="${0##*/}"
+LOCKFILE="$VIBRANIUM_RUNTIME/$SELF.lock"
 
+shcat() {
+  while IFS= read -r line; do
+    printf '%s\n' "$line"
+  done
+}
+
+usage() {
+  shcat <<EOF
+Usage: ${0##*/} [OPTIONS]
+
+Open / close rofi-based calculator.
+
+Options:
+  -h, --help Show this help and exit
+EOF
+}
+
+case "$1" in
+-h | --help)
+  usage
+  exit 0
+  ;;
+-* | --*)
+  echo "Error: unknown option: '$1'" >&2
+  echo "Try '$SELF --help' for more information" >&2
+  exit 1
+  ;;
+*)
+  echo "Ignoring input '$@'"
+  ;;
+esac
+
+exec 9>"$LOCKFILE"
+
+# Killswitch
 if ! flock -n 9; then
-  pkill -f "rofi.*-show calc" 2> /dev/null
+  pkill -f "rofi.*-show calc" 2>/dev/null
   exit 0
 fi
 
@@ -14,12 +50,12 @@ if [[ ! -f /usr/lib/rofi/libcalc.so ]]; then
 fi
 
 theme_str="$(
-  cat << EOF
+  shcat <<EOF
 window {
-    width: 500;
+    width: 30%;
 }
 entry {
-    placeholder: " expression";
+    placeholder: ' expression';
 }
 listview, num-rows, textbox-num-sep, num-filtered-rows {
     enabled: false;
