fix: the case statement would block initial checks

diff --git a/bin/vb-core-screenshot b/bin/vb-core-screenshot
--- a/bin/vb-core-screenshot
+++ b/bin/vb-core-screenshot
@@ -139,6 +139,17 @@ init() {
     fi
 }
 
+if slurp_pid="$(pidof slurp)"; then
+    kill $slurp_pid
+    exit 1
+fi
+
+if ! missing="$(vb-cmd-is-present grim slurp jq)"; then
+    log::error "missing required dependencies: $missing"
+    term::is_headless && vb-cmd-dep-notify --name "Clipboard Manager" --deps "$missing"
+    exit 1
+fi
+
 case "$1" in
     --region|--window|--screen)
         init
@@ -154,15 +165,3 @@ case "$1" in
         exit 1
         ;;
 esac
-
-if ! missing="$(vb-cmd-is-present grim slurp jq)"; then
-    log::error "missing required dependencies: $missing"
-    term::is_headless && vb-cmd-dep-notify --name "Clipboard Manager" --deps "$missing"
-    exit 1
-fi
-
-if slurp_pid="$(pidof slurp)"; then
-    kill $slurp_pid
-    exit 1
-fi
-
