fix: okay make gsr not available in a vm

diff --git a/bin/vb-core-recording b/bin/vb-core-recording
--- a/bin/vb-core-recording
+++ b/bin/vb-core-recording
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [[ $CHASSIS_TYPE == vm ]]; then
+  echo "Error: screen recording isn't available in a VM!" >&2
+  exit 1
+fi
+
 source vb-lib-core
 
 LOG_FILE="$VIBRANIUM_CACHE/${0##*/}.log"
@@ -70,7 +75,7 @@ set_rec_area() {
 init_recording() {
   local opt_flags=()
 
-  if [[ ! -z ${1:-} ]] || [[ $CHASSIS_TYPE == vm ]]; then
+  if [[ ! -z ${1:-} ]]; then
     opt_flags=(-encoder cpu)
   fi
 
diff --git a/bin/vb-menu-recording b/bin/vb-menu-recording
--- a/bin/vb-menu-recording
+++ b/bin/vb-menu-recording
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
 
+if [[ $CHASSIS_TYPE == vm ]]; then
+  notify-send "Screen Recorder" "screen recording isn't available in a VM!"
+  echo "Error: screen recording isn't available in a VM!" >&2
+  exit 1
+fi
+
 if pidof -q rofi; then
   killall rofi
   exit 0
