refactor(general): make alacritty.service mandatory to run

diff --git a/bin/vb-cmd-terminal b/bin/vb-cmd-terminal
--- a/bin/vb-cmd-terminal
+++ b/bin/vb-cmd-terminal
@@ -15,7 +15,6 @@ Options:
 EOF
 }
 
-# CLI parsing
 case "${1:-}" in
     -h|--help)
         usage
@@ -23,17 +22,19 @@ case "${1:-}" in
         ;;
 esac
 
-# ensure Alacritty service is running
-# if [[ "$(systemctl --user is-active alacritty)" != "active" ]]; then
-#     systemctl --user enable --now alacritty
-# fi
-
 args=()
 
-# If a command is provided, pass -e and the command; otherwise just open terminal
 if [[ $# -ge 1 ]]; then
-    args+=(-e "$@")
+    cmd="$1"
+
+    if ! command -v "$cmd" > /dev/null; then
+        echo "$cmd: command not found"
+        exit 1
+    fi
+
+    shift
+    class="$(basename -- "$cmd")"
+    args=(-e "$cmd" "$@")
 fi
 
-# exec setsid uwsm app -- alacritty msg create-window "${args[@]}"
-alacritty msg create-window "${args[@]}"
+alacritty msg create-window --class "$class" --title "$class" "${args[@]}"
