refactor!(installer): refactor the installer from scratch. Bare bone version for now

diff --git a/install/install b/install/install
--- a/install/install
+++ b/install/install
@@ -7,12 +7,19 @@ EXPECTED_PATH="$HOME/.local/share/vibranium/install"
 VIBRANIUM="$HOME/.local/share/vibranium"
 
 if [[ "$SCRIPT_DIR" != "$EXPECTED_PATH" ]]; then
-  echo "ERROR: This script must be run from $EXPECTED_PATH"
-  echo "Current location: $SCRIPT_DIR"
+  echo "ERROR: This script must be run from $EXPECTED_PATH" >&2
+  echo "Current location: $SCRIPT_DIR" >&2
   echo ""
-  echo "Please move the dotfiles folder to ~/.local/share/vibranium and try again"
+  echo "Please move the vibranium folder to ~/.local/share/vibranium and try again" >&2
   exit 1
 fi
+
+_sudo_loop() {
+    while true; do
+        sudo -v
+        sleep 10
+    done
+}
 
 # Source helpers
 source "$SCRIPT_DIR/lib/helpers.sh"
@@ -28,6 +35,7 @@ export SUDO_PROMPT
 # fi
 
 echo -e "${YELLOW}[VIBRANIUM]${RESET} Vibranium needs sudo to install packages"
+
 if ! sudo -v; then
     exit 1
 fi
@@ -36,27 +44,47 @@ clear
 
 # Move VT to the bottom
 printf '\e[2J\e[%d;1H' "${LINES:-$(tput lines)}"
-_show_logo
 
-TOTAL_STEPS=10
+# Hide cursor
+printf '\e[?25l'
+
+_show_logo
+_sudo_loop &
+
+YAY_PRESENT="$(_is_installed yay && echo true || echo false)"
+
 CURRENT_STEP=0
 
-mapfile -t PACKAGES < "$VIBRANIUM/pkg_list.txt"
+if [[ "$YAY_PRESENT" == true ]]; then
+    TOTAL_STEPS=12
+else
+    TOTAL_STEPS=11
+fi
+
+mapfile -t PACKAGES < "$SCRIPT_DIR/pkgs.txt"
 
 CURRENT_STEP=$((CURRENT_STEP + 1))
 _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Setting up system"
+{
+    bash "$SCRIPT_DIR/setup-system"
+    bash "$SCRIPT_DIR/setup-tmpfiles"
+    bash "$SCRIPT_DIR/setup-sysctl"
+    bash "$SCRIPT_DIR/setup-zram"
+}
 
-bash "$SCRIPT_DIR/setup-system"
-bash "$SCRIPT_DIR/setup-tmpfiles"
-bash "$SCRIPT_DIR/setup-sysctl"
-bash "$SCRIPT_DIR/setup-zram"
-
-if ! _is_installed "yay"; then
-    TOTAL_STEPS=11
+# I want to install yay first,
+# but we have to keep this step here for now
+# because we're modifying the main pacman config above.
+#
+# Later I’ll reorder this so that pacman.conf
+# and makepkg.conf are updated first,
+# then yay is installed,
+# and only after that system files / configs are set up.
+[[ "$YAY_PRESENT" == true ]] {
     CURRENT_STEP=$((CURRENT_STEP + 1))
     _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing yay AUR helper"
     _install_yay
-fi
+}
 
 CURRENT_STEP=$((CURRENT_STEP + 1))
 _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Installing packages"
@@ -101,3 +129,13 @@ CURRENT_STEP=$((CURRENT_STEP + 1))
 _log_info "[$CURRENT_STEP/$TOTAL_STEPS] Finishing up"
 bash "$SCRIPT_DIR/post-install"
 
+_log_success "Installation complete. System restart required"
+
+sleep 1
+
+for i in {5..1}; do
+    printf "\r\033[K%s[VIBRANIUM]%s Restarting PC in %d..." "$YELLOW" "$RESET" "$i"
+    sleep 0.25
+done
+
+systemctl reboot
